### ISSUE TITLE
Add support for iOS. 

### ISSUE THREAD

**Issue by seivan** [RustAudio/coreaudio-sys#29]
This [PR](https://github.com/RustAudio/coreaudio-sys/pull/28) does most of the work but it's not enough. Certain headers don't exist on `iOS` like `"CoreAudio/CoreAudio.h"` itself, but you can add `"CoreAudio/CoreAudioTypes.h"`

Related to https://github.com/RustAudio/coreaudio-rs/issues/67

**Comment by MichaelHills** [comment]
Fixed by https://github.com/RustAudio/coreaudio-sys/pull/33
