### ISSUE TITLE
Failed to compile on MacOS

### ISSUE THREAD

**Issue by SnowyThinker** [RustAudio/coreaudio-sys#79]
--------------------------------------------------------------------
BigMac:bevy_chess andrew$ cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

--------------------------------------------------------------------
error: failed to run custom build command for `coreaudio-sys v0.2.5`

Caused by:
  process didn't exit successfully: `/Users/andrew/workbench/souce/rust/bevy_chess/target/debug/build/coreaudio-sys-1b809ab8d23227a9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX13_1_sdk/usr/include/MacTypes_h_382_1)" is not a valid Ident', /Users/andrew/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/proc-macro2-1.0.56/src/fallback.rs:811:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
--------------------------------------------------------------------

**Comment by nwang92** [comment]
I had a similar issue and with some inspiration from https://github.com/RustAudio/coreaudio-sys/issues/25#issuecomment-497227012, I was able to resolve it by uninstalling llvm:
```
brew uninstall llvm
```

**Comment by EricHenry** [comment]
> I had a similar issue and with some inspiration from [#25 (comment)](https://github.com/RustAudio/coreaudio-sys/issues/25#issuecomment-497227012), I was able to resolve it by uninstalling llvm:
> 
> ```
> brew uninstall llvm
> ```

This worked for me too.

**Comment by SnowyThinker** [comment]
It works. 😃
