### ISSUE TITLE
Compilation fails with Rust 1.73.0 and Xcode 15

### ISSUE THREAD

**Issue by markusmoenig** [RustAudio/coreaudio-sys#89]
thread 'main' panicked at /Users/markusmoenig/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:811:9:
  "enum_(unnamed_at_/Applications/Xcode_app/Contents/Developer/Platforms/MacOSX_platform/Developer/SDKs/MacOSX14_0_sdk/usr/include/MacTypes_h_382_1)" is not a valid Ident

**Comment by simlay** [comment]
I'm willing to bet that this is a dupe of #85. I'm not sure what your dependency tree looks like. Most things using `coreaudio-sys` are using semver. I merged (and published) a non-breaking change to coreaudio-sys with #86 to fix this issue. Hopefully `cargo update` fixes your issue. This updates any non-locked patch versions of crates.

**Comment by markusmoenig** [comment]
Yes, this fixes it, thanks a lot!
